interface CountryFlagProps {
  countryCode?: string;
  countryName?: string;
  className?: string;
  showName?: boolean;
}

// Map of country codes to flag emojis
const countryFlags: Record<string, string> = {
  'US': '🇺🇸',
  'GB': '🇬🇧',
  'DE': '🇩🇪',
  'FR': '🇫🇷',
  'IT': '🇮🇹',
  'ES': '🇪🇸',
  'NL': '🇳🇱',
  'BE': '🇧🇪',
  'AT': '🇦🇹',
  'CH': '🇨🇭',
  'CZ': '🇨🇿',
  'PL': '🇵🇱',
  'SK': '🇸🇰',
  'HU': '🇭🇺',
  'RO': '🇷🇴',
  'BG': '🇧🇬',
  'HR': '🇭🇷',
  'SI': '🇸🇮',
  'RS': '🇷🇸',
  'BA': '🇧🇦',
  'ME': '🇲🇪',
  'MK': '🇲🇰',
  'AL': '🇦🇱',
  'GR': '🇬🇷',
  'TR': '🇹🇷',
  'RU': '🇷🇺',
  'UA': '🇺🇦',
  'BY': '🇧🇾',
  'LT': '🇱🇹',
  'LV': '🇱🇻',
  'EE': '🇪🇪',
  'FI': '🇫🇮',
  'SE': '🇸🇪',
  'NO': '🇳🇴',
  'DK': '🇩🇰',
  'IS': '🇮🇸',
  'IE': '🇮🇪',
  'PT': '🇵🇹',
  'LU': '🇱🇺',
  'MC': '🇲🇨',
  'AD': '🇦🇩',
  'SM': '🇸🇲',
  'VA': '🇻🇦',
  'MT': '🇲🇹',
  'CY': '🇨🇾',
  'CA': '🇨🇦',
  'MX': '🇲🇽',
  'BR': '🇧🇷',
  'AR': '🇦🇷',
  'CL': '🇨🇱',
  'CO': '🇨🇴',
  'PE': '🇵🇪',
  'VE': '🇻🇪',
  'UY': '🇺🇾',
  'PY': '🇵🇾',
  'BO': '🇧🇴',
  'EC': '🇪🇨',
  'GY': '🇬🇾',
  'SR': '🇸🇷',
  'GF': '🇬🇫',
  'JP': '🇯🇵',
  'KR': '🇰🇷',
  'CN': '🇨🇳',
  'TW': '🇹🇼',
  'HK': '🇭🇰',
  'MO': '🇲🇴',
  'SG': '🇸🇬',
  'MY': '🇲🇾',
  'TH': '🇹🇭',
  'VN': '🇻🇳',
  'PH': '🇵🇭',
  'ID': '🇮🇩',
  'IN': '🇮🇳',
  'PK': '🇵🇰',
  'BD': '🇧🇩',
  'LK': '🇱🇰',
  'NP': '🇳🇵',
  'BT': '🇧🇹',
  'MV': '🇲🇻',
  'AU': '🇦🇺',
  'NZ': '🇳🇿',
  'FJ': '🇫🇯',
  'PG': '🇵🇬',
  'SB': '🇸🇧',
  'VU': '🇻🇺',
  'NC': '🇳🇨',
  'PF': '🇵🇫',
  'WS': '🇼🇸',
  'TO': '🇹🇴',
  'KI': '🇰🇮',
  'TV': '🇹🇻',
  'NR': '🇳🇷',
  'PW': '🇵🇼',
  'FM': '🇫🇲',
  'MH': '🇲🇭',
  'ZA': '🇿🇦',
  'EG': '🇪🇬',
  'MA': '🇲🇦',
  'TN': '🇹🇳',
  'DZ': '🇩🇿',
  'LY': '🇱🇾',
  'SD': '🇸🇩',
  'ET': '🇪🇹',
  'KE': '🇰🇪',
  'UG': '🇺🇬',
  'TZ': '🇹🇿',
  'RW': '🇷🇼',
  'BI': '🇧🇮',
  'DJ': '🇩🇯',
  'SO': '🇸🇴',
  'ER': '🇪🇷',
  'SS': '🇸🇸',
  'CF': '🇨🇫',
  'TD': '🇹🇩',
  'CM': '🇨🇲',
  'GQ': '🇬🇶',
  'GA': '🇬🇦',
  'CG': '🇨🇬',
  'CD': '🇨🇩',
  'AO': '🇦🇴',
  'ZM': '🇿🇲',
  'ZW': '🇿🇼',
  'BW': '🇧🇼',
  'NA': '🇳🇦',
  'SZ': '🇸🇿',
  'LS': '🇱🇸',
  'MW': '🇲🇼',
  'MZ': '🇲🇿',
  'MG': '🇲🇬',
  'MU': '🇲🇺',
  'SC': '🇸🇨',
  'KM': '🇰🇲',
  'YT': '🇾🇹',
  'RE': '🇷🇪',
  'SH': '🇸🇭',
  'ST': '🇸🇹',
  'CV': '🇨🇻',
  'GW': '🇬🇼',
  'GN': '🇬🇳',
  'SN': '🇸🇳',
  'GM': '🇬🇲',
  'GH': '🇬🇭',
  'TG': '🇹🇬',
  'BJ': '🇧🇯',
  'NE': '🇳🇪',
  'BF': '🇧🇫',
  'ML': '🇲🇱',
  'CI': '🇨🇮',
  'LR': '🇱🇷',
  'SL': '🇸🇱',
  'IL': '🇮🇱',
  'PS': '🇵🇸',
  'JO': '🇯🇴',
  'LB': '🇱🇧',
  'SY': '🇸🇾',
  'IQ': '🇮🇶',
  'IR': '🇮🇷',
  'AF': '🇦🇫',
  'KW': '🇰🇼',
  'SA': '🇸🇦',
  'BH': '🇧🇭',
  'QA': '🇶🇦',
  'AE': '🇦🇪',
  'OM': '🇴🇲',
  'YE': '🇾🇪',
  'GE': '🇬🇪',
  'AM': '🇦🇲',
  'AZ': '🇦🇿',
  'KZ': '🇰🇿',
  'KG': '🇰🇬',
  'TJ': '🇹🇯',
  'TM': '🇹🇲',
  'UZ': '🇺🇿',
  'MN': '🇲🇳',
};

export function CountryFlag({ countryCode, countryName, className = '', showName = false }: CountryFlagProps) {
  if (!countryCode) {
    return null;
  }

  const flag = countryFlags[countryCode.toUpperCase()];
  
  if (!flag) {
    return null;
  }

  return (
    <span className={`inline-flex items-center gap-1 ${className}`}>
      <span className="text-base" role="img" aria-label={countryName || countryCode}>
        {flag}
      </span>
      {showName && countryName && (
        <span className="text-xs text-gray-600">{countryName}</span>
      )}
    </span>
  );
}
